### ISSUE TITLE
Fork and mismatching state snapshot hash in TestMirBasic_WithFOmissionNodes

### ISSUE THREAD

**Issue by dnkolegov** [consensus-shipyard/lotus#95]
Steps to reproduce:
1. Use the branch [issue93](https://github.com/consensus-shipyard/lotus/tree/issue93)
2. Run
```
GOLOG_LOG_LEVEL="warn,mir-consensus=info,mir-manager=info" go test -tags=spacenet -v  -run TestMirBasic_WithFOmissionNodes ./itests/mir_test.go | tee log.txt
```
A fork happens if it does not stop before the height of 60.

**Comment by matejpavlovic** [comment]
A PR “Fix issue95” has been merged, but the issue is still open. If I remember correctly, @dnkolegov you said that there are still inconsistencies in the snapshots, despite that PR. Is that the case? Is this reproducible on the spacenet branch? Let's wait for merging #115 and try to reproduce it there, in case the fixes introduced there also resolve this...
If I'm wrong and this issue is obsolete, let's close it.

**Comment by dnkolegov** [comment]
We can close it. The bug is not reproduced.
